### ISSUE TITLE
Requiring rspec

### ISSUE THREAD

**Issue by MikeNGarrett** [flood-io/flood-capybara#1]
I'm having some trouble with this script. Running `flood-capybara` results in the following error and trace below.
Requiring rspec makes sense, but I already have that included in my gem file, as well as requires for rspec/rails and capybara/rspec in my rails_helper. 
Without flood-capybara I'm able to run bundle exec rspec spec without any error. 

```
.rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- rspec (LoadError)
    from .rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from .rvm/gems/ruby-2.1.6/gems/flood-capybara-0.0.4/lib/flood-capybara/application.rb:1:in `<top (required)>'
    from .rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from .rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from .rvm/gems/ruby-2.1.6/gems/flood-capybara-0.0.4/lib/flood-capybara.rb:10:in `<top (required)>'
    from .rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from .rvm/rubies/ruby-2.1.6/lib/ruby/site_ruby/2.1.0/rubygems/core_ext/kernel_require.rb:54:in `require'
    from .rvm/gems/ruby-2.1.6/gems/flood-capybara-0.0.4/bin/flood-capybara:3:in `<top (required)>'
    from .rvm/gems/ruby-2.1.6/bin/flood-capybara:23:in `load'
    from .rvm/gems/ruby-2.1.6/bin/flood-capybara:23:in `<main>'
```

**Comment by 90kts** [comment]
No longer maintained
