### ISSUE TITLE
Unable to run the sample spec

### ISSUE THREAD

**Issue by kevinjqiu** [flood-io/flood-capybara#2]
There's a couple of problems I found while trying to get a test running:
1. The README (https://github.com/flood-io/flood-capybara/commit/b872cbf6a7469ea8488c5cb63a89cd7e39f5892f#diff-04c6e90faac2675aa89e2176d2eec7d8R30) is missing `--tag` , which causes the following error when I run:

```
$ flood-capybara spec --api-token=XXX --grid=YYY --rampup=30 --duration=30 --url=http://pt.ssogateway.points.com
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.7-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
/home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/flood-capybara/application.rb:15:in `+': no implicit conversion of nil into Array (TypeError)
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/flood-capybara/application.rb:15:in `run'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/cli/application.rb:19:in `spec'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/bin/flood-capybara:5:in `<top (required)>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `load'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `<main>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

This particular error goes away when I add `--tag=flood` to the command line.
1. Missing yaml

```
/home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/flood-capybara/application.rb:20:in `run': undefined method `to_yaml' for []:Array (NoMethodError)
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/cli/application.rb:18:in `spec'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/bin/flood-capybara:5:in `<top (required)>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `load'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `<main>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

This is fixed by `require 'yaml'` in the code
1. ``run': undefined method`try' for []:Array (NoMethodError)`

After adding yaml to the source code, I got this

```
flood-capybara spec --api-token=XXX --grid=YYY --rampup=30 --duration=30 --url=http://pt.ssogateway.points.com --tag=flood
warning: parser/current is loading parser/ruby21, which recognizes
warning: 2.1.7-compliant syntax, but you are running 2.1.5.
warning: please see https://github.com/whitequark/parser#compatibility-with-ruby-mri.
I, [2015-11-18T21:06:43.340818 #7158]  INFO -- : Flood specs: 
--- []

/home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/flood-capybara/application.rb:24:in `run': undefined method `try' for []:Array (NoMethodError)
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/lib/cli/application.rb:19:in `spec'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
    from /home/kevin/.rvm/gems/ruby-2.1.5/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bundler/gems/flood-capybara-d41fb29e525e/bin/flood-capybara:5:in `<top (required)>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `load'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/flood-capybara:23:in `<main>'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `eval'
    from /home/kevin/.rvm/gems/ruby-2.1.5/bin/ruby_executable_hooks:15:in `<main>'
```

and I have no idea how to fix this.  Please advise.

**Comment by 90kts** [comment]
No longer maintained
